Repository xKDR/Survey.jl, pull requests merged in 2023-01, with the labels that each got.

#172 Update survey design, add tests, remove extra quantile, add `design.weights`
  .gitignore
  src/SurveyDesign.jl
  src/bootstrap.jl
  src/by.jl
  src/hist.jl
  src/mean.jl
  src/plot.jl
  src/quantile.jl
  src/ratio.jl
  src/show.jl
  src/total.jl
  test/SurveyDesign.jl
  test/plot.jl
  test/show.jl
Labels: documentation, enhancement, high priority, testing, india visit

#183 Add SE for quantile
  src/quantile.jl
  test/quantile.jl
Labels: enhancement

#155 WIP: SingleStageSurveyDesign for one cluster, one strata and one weights
  src/Survey.jl
  src/SurveyDesign.jl
  src/show.jl
  test/SurveyDesign.jl
Labels: enhancement

#193 Restructure documentation
  docs/make.jl
  docs/src/R_comparison.md
  docs/src/api.md
  docs/src/getting_started.md
  docs/src/index.md
  docs/src/man/comparisons.md
  docs/src/man/dataframes.md
  docs/src/man/future.md
  docs/src/man/plotting.md
  docs/src/man/replicate.md
  src/SurveyDesign.jl
  src/bootstrap.jl
  src/boxplot.jl
  src/hist.jl
  src/plot.jl
  src/quantile.jl
  src/ratio.jl
Labels: documentation, high priority

#181 WIP: Merge `singledesign` into `main`
  .gitignore
  Project.toml
  README.md
  docs/make.jl
  docs/src/R_comparison.md
  docs/src/api.md
  docs/src/getting_started.md
  docs/src/index.md
  docs/src/man/comparisons.md
  docs/src/man/dataframes.md
  docs/src/man/future.md
  docs/src/man/plotting.md
  docs/src/man/replicate.md
  src/Survey.jl
  src/SurveyDesign.jl
  src/bootstrap.jl
  src/boxplot.jl
  src/by.jl
  src/dimnames.jl
  src/hist.jl
  src/jackknife.jl
  src/mean.jl
  src/plot.jl
  src/quantile.jl
  src/ratio.jl
  src/show.jl
  src/total.jl
  test/SurveyDesign.jl
  test/bootstrap.jl
  test/boxplot.jl
  test/dimnames.jl
  test/hist.jl
  test/jackknife.jl
  test/mean.jl
  test/plot.jl
  test/quantile.jl
  test/ratio.jl
  test/runtests.jl
  test/sampling.jl
  test/show.jl
  test/total.jl
Labels: enhancement, high priority
